
* Ansible


** Installing Ansible.

#+BEGIN_SRC bash
sudo apt update
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

#+END_SRC


  
** Concepts

*** Control Node

Control Node is the machine from where you manage configuration on
other servers/devices. Any machine running Linux or Mac OS with python
can be used as a Ansible Control node. Install Ansible and you're
ready to go with a few configurations.


*** Managed Node

Any network device or server  that is managed with Ansible is called as Managed Node. They are referred to as hosts. No Ansible agent needs to be installed on the worker nodes.

*** Inventory

An inventory file is a  list of the nodes that are to be managed by Ansible from control node. 
An inventory is also known as "hostfile"

*** Module
A module is a unit of code that Ansible executes and each module has a particular use.
User Management to managing VLAN to provisioning infrastructure, there is a module for each of the activities. 
Ansible come with a lot of modules for each activity.


Some of the frequently used Modules.

[[https://docs.ansible.com/ansible/latest/modules/modules_by_category.html][Ansible Modules]]

- setup
- shell
- apt/yum
- service
- copy
- file /template
- lineinfile



*** Tasks
A module in use is called as a task. 
For example, using `yum` module to install a certain package is a task.
Tasks can be run ad-hoc

*** Playbooks
A list of tasks together is known as a Playbook. 
They are written in YAML.
Playbooks can also include variables along with tasks.

*** Inventory

Inventory is the list of servers and their related information such as 




** Setting up inventory

By default ansible's inventory file or hostfile is located at `/etc/ansible/hosts`
This file can be updated with the list of your managed nodes and they can be grouped into different groups.
For instance you can have a group of web servers and another group for DB servers 
Inventory file is a simple text file. 

Example inventory file:

#+BEGIN_SRC

[web]
192.168.10.1
192.168.10.2

[db]
192.168.10.5
192.168.10.6

#+END_SRC

We could use a custom inventory file by using the i switch

#+BEGIN_SRC 
ansible -i <inventory-file> <commands>
#+END_SRC


When adding control node to the inventory add the below line so that ansible wouldn't try to ssh into the control machine as well.
local 
`ansible_collection=local` 

*** Working with playbooks

Playbooks are a set of steps that can be performed in sequence or in parallel.
Playbooks are written in YAML.

*** Sample Play Book

#+BEGIN_SRC yaml

---

- hosts: web       # Group of servers defined in the inventory
  become: true     # To become sudo user while executing the belo tasks

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present
   
 
#+END_SRC


*** Run a playbook

The taks executed inside a playbook can be executed by running below command

#+BEGIN_SRC bash

ansible-playbook -i <hostsfile> </path/to/ansible/playbook>

#+END_SRC

In the command hosts file is where you save the inventory. If you don't use `-i` option, the default inventory which is '/etc/ansible/hosts' 






